### ISSUE TITLE
マルチアーキテクチャのテストをできるようにする

### ISSUE THREAD

**Issue by miminashi** [machikado-network/sakura#1]
こういう凡ミスがあるのでテストできるようにしたい
https://discord.com/channels/1005024217143705642/1005024217584123916/1006937405892345957

**Comment by sizumita** [comment]
終わりました

**Comment by miminashi** [comment]
@sizumita 当該するpull reqまたはコミットへのリンクを貼っておいてほしいかも

**Comment by sizumita** [comment]
https://github.com/machikado-network/machikado.network/commit/5464c303e781332a53a228c0b874ad8b33a9c84b
です
