### ISSUE TITLE
セットアップスクリプトにオプションパラメータを渡せない

### ISSUE THREAD

**Issue by miminashi** [machikado-network/sakura#2]
https://discord.com/channels/1005024217143705642/1005024217584123916/1006939088869396612
ワンライナーとスクリプト本体を修正して渡せるようにする

**Comment by miminashi** [comment]
これ https://github.com/machikado-network/machikado.network のほうのタスクだな

**Comment by sizumita** [comment]
`export INSTALL_PATH=/usr/local/bin && curl -sL https://machikado.network/install/sakura | bash`でできるようにはなりました
