### ISSUE TITLE
ブリッジインターフェース名を渡せるようにする

### ISSUE THREAD

**Issue by miminashi** [machikado-network/sakura#6]
`br0` が既に使用中だと以下のような事故が起きる。

https://discord.com/channels/406357894427312148/1005025504547586128/1006180102020796546
https://discord.com/channels/406357894427312148/1005025504547586128/1006182017844662334

そこで、

- ブリッジインターフェース名を指定できるようにする
- 指定したブリッジインターフェースが既に使用中の場合、セットアップをアボートする

**Comment by sizumita** [comment]
> 指定したブリッジインターフェースが既に使用中の場合、セットアップをアボートする

これはあまり需要がないと思うので、インターフェース名を指定できれば良いと思う

**Comment by miminashi** [comment]
br0を勝手に上書きされると困るという話なので、むしろそこが重要なんだけど

**Comment by sizumita** [comment]
なるほど

**Comment by miminashi** [comment]
この手のプロジェクトに興味持つ人のことなので、既に別のVPNやらをつかってる可能性もあり、その場合br0を既に使ってる可能性が高い。
極力安全な振る舞いをしたほうがよさそう。

**Comment by sizumita** [comment]
ブリッジインターフェースが既に使用中かどうか確認する方法はある？

**Comment by miminashi** [comment]
ip link show br0 で確認できるよ

**Comment by sizumita** [comment]
理解した
